# Generated by Django 4.2.10 on 2024-03-23 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='Url', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TranslationHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('lng', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('de', 'German'), ('ja', 'Japanese'), ('pt', 'Portuguese'), ('nl', 'Dutch'), ('it', 'Italian')], max_length=10, null=True)),
                ('header', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.header')),
                ('url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.url')),
            ],
        ),
        migrations.CreateModel(
            name='TranslationFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('lng', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('de', 'German'), ('ja', 'Japanese'), ('pt', 'Portuguese'), ('nl', 'Dutch'), ('it', 'Italian')], max_length=10, null=True)),
                ('footer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.footer')),
            ],
        ),
        migrations.CreateModel(
            name='SubHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('translation_header', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.translationheader')),
                ('url', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.url')),
            ],
        ),
        migrations.CreateModel(
            name='SubFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('translation_footer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.translationfooter')),
                ('url', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.url')),
            ],
        ),
    ]
