# Generated by Django 4.2.10 on 2024-03-23 18:07

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(choices=[('Home', 'Home'), ('JPG to PDF', 'JPG to PDF'), ('HEIC to JPG', 'HEIC to JPG'), ('Image to PDF', 'Image to PDF'), ('PNG TO JPG', 'PNG TO JPG'), ('MP3 Converter', 'MP3 Converter'), ('MP4 to MP3', 'MP4 to MP3'), ('Video to MP3', 'Video to MP3'), ('Image to Word', 'Image to Word')], max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToolPageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('de', 'German'), ('ja', 'Japanese'), ('pt', 'Portuguese'), ('nl', 'Dutch'), ('it', 'Italian')], max_length=10, null=True)),
                ('short_desc', models.TextField(max_length=100, null=True)),
                ('title', models.CharField(max_length=500, null=True)),
                ('description', tinymce.models.HTMLField()),
                ('tool_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tool.toolpage')),
                ('url', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.url')),
            ],
            options={
                'unique_together': {('tool_page', 'language')},
            },
        ),
    ]
