# Generated by Django 4.2.10 on 2024-04-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolpage',
            name='tool',
            field=models.CharField(choices=[('Home', 'Home'), ('HEIC to JPG', 'HEIC to JPG'), ('PNG TO JPG', 'PNG TO JPG'), ('JPG TO PNG', 'JPG TO PNG'), ('MP4 to MP3', 'MP4 to MP3'), ('Video to MP3', 'Video to MP3'), ('Image to Word', 'Image to Word'), ('MP3 Convertor', 'MP3 Convertor'), ('Audio Convertor', 'Audio Convertor')], max_length=100, null=True, unique=True),
        ),
    ]
