# Generated by Django 4.2.10 on 2024-05-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_toolpage_custom_url_alter_toolpage_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolpage',
            name='custom_url',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
