# Generated by Django 4.2.10 on 2024-05-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_alter_toolpage_custom_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolpage',
            name='custom_url',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
