# Generated by Django 4.2.10 on 2025-05-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0005_alter_toolpage_custom_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpagetranslation',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='toolpagetranslation',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='toolpagetranslation',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='toolpagetranslation',
            name='og_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='toolpagetranslation',
            name='og_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='toolpagetranslation',
            name='og_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='toolpagetranslation',
            name='og_type',
            field=models.CharField(blank=True, default='website', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='toolpagetranslation',
            name='og_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='toolpagetranslation',
            name='twitter_card',
            field=models.CharField(blank=True, default='summary', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='toolpagetranslation',
            name='twitter_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='toolpagetranslation',
            name='twitter_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='toolpagetranslation',
            name='twitter_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
